# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

create_high_qual_training_set_mode: True
create_debug_dataset_mode: False
preprocess_mode: False
experiment_mode: False


dir_preprocessed: ${work_dir}/data/DocRED_preprocessed
