# @package _global_

# default running mode

default_mode: True
preprocess_mode: False
create_debug_dataset_mode: False
create_high_qual_training_set_mode: False


hydra:
  # default output paths for all file logs
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}