# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

experiment_mode: True
create_debug_dataset_mode: False
preprocess_mode: False
create_high_qual_training_set_mode: False

# allows for custom naming of the experiment

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: logs/experiments/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/experiments/${name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
