# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

preprocess_mode: True
experiment_mode: False
create_debug_dataset_mode: False
create_high_qual_training_set_mode: False

model_type: 'bert'
model_name_or_path: 'bert-base-uncased'

#model_type: 'roberta'
#model_name_or_path: 'roberta-base'

max_seq_length: 512
do_lower_case: True
ratio: 1.0

# Data directories
data_dir: ${work_dir}/data/docred
#data_dir: ${work_dir}/data/pretrain_data
erica_pretrain_data: False

